services:
  zookeeper:
    container_name: zookeeper
    image: quay.io/debezium/zookeeper:3.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    container_name: kafka
    image: quay.io/debezium/kafka:3.0
    ports:
     - 9092:9092
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
     - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    depends_on:
     - zookeeper
  connect:
    container_name: connect
    image: quay.io/debezium/connect:3.0
    ports:
     - 8083:8083
    volumes:
     - ./jdbc:/kafka/connect/jdbc
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_connect_statuses
     - CONNECT_PLUGIN_PATH=/kafka/connect
    depends_on:
     - kafka
  mysql_source:
    container_name: mysql_source
    image: mysql:8.0
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=mysqlsource
     - MYSQL_PASSWORD=mysqlsource
  mysql_target:
    container_name: mysql_target
    image: mysql:8.0
    ports:
     - 3307:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=mysqltarget
     - MYSQL_PASSWORD=mysqltarget